[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "node-template"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.1.4"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sr-io = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
primitives = { package = "substrate-primitives", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-executor = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-service = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
inherents = { package = "substrate-inherents", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
transaction-pool = { package = "substrate-transaction-pool", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
network = { package = "substrate-network", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
babe = { package = "substrate-consensus-babe", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
grandpa = { package = "substrate-finality-grandpa", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-client = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
basic-authorship = { package = "substrate-basic-authorship", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

# This will not currently build unless you have the runtime in the right spot
# Would be nice to bring this in from git dependency
# See <insert issue about workspaces here>
runtime = { package = "super-node-runtime", path = "../recipes/kitchen/runtimes/super-node-runtime" }
runtime-genesis = { package = "super-node-genesis", path = "../recipes/kitchen/runtimes/super-node-genesis" }

[build-dependencies]
vergen = "3.0.4"
